using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public static class AlphabetLists
{
    public static List<char> listAllAlphabets = new()
    {
        'A',
        'B',
        'C',
        'D',
        'E',
        'F',
        'G',
        'H',
        'I',
        'J',
        'K',
        'L',
        'M',
        'N',
        'O',
        'P',
        'Q',
        'R',
        'S',
        'T',
        'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'Á',
        'Â',
        'Ã',
        'À',
        'Ç',
        'É',
        'Ê',
        'Ë',
        'È',
        'Ù',
        'Ü',
        'Ú',
        'Û',
        'Í',
        'Î',
        'Ï',
        'Ó',
        'Ô',
        'Õ',
        'Æ',
        'Œ',
        'Б',
        'В',
        'Г',
        'Д',
        'Е',
        'Ё',
        'Ж',
        'З',
        'И',
        'Й',
        'К',
        'Л',
        'М',
        'Н',
        'О',
        'П',
        'Р',
        'С',
        'Т',
        'У',
        'Ф',
        'Х',
        'Ц',
        'Ч',
        'Ш',
        'Щ',
        'Ъ',
        'Ы',
        'Ь',
        'Э',
        'Ю',
        'Я'
    };
    public static List<char> englishAlphabet = new()
    {
        'A', 'A', 'A', 'A', 'A',
        'B',
        'C',
        'D',
        'E', 'E', 'E', 'E', 'E',
        'F',
        'G',
        'H',
        'I', 'I', 'I', 'I',
        'J',
        'K',
        'L', 'L',
        'M',
        'N', 'N', 'N',
        'O', 'O', 'O',
        'P',
        'Q',
        'R', 'R', 'R', 'R',
        'S', 'S',
        'T', 'T', 'T',
        'U', 'U',
        'V',
        'W',
        'X',
        'Y',
        'Z'
    };
    public static List<char> malaysiaAlphabet = new()
    {
        'A', 'A', 'A', 'A', 'A',
        'B',
        'C',
        'D',
        'E', 'E', 'E', 'E', 'E',
        'F',
        'G',
        'H',
        'I', 'I', 'I', 'I',
        'J',
        'K', 'K',
        'L', 'L',
        'M', 'M', 'M',
        'N', 'N', 'N',
        'O',
        'P',
        'Q',
        'R', 'R', 'R',
        'S', 'S',
        'T',
        'U', 'U', 'U', 'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
    };
    public static List<char> indonesiaAlphabet = new()
    {
        'A', 'A', 'A', 'A', 'A',
        'B',
        'C',
        'D',
        'E', 'E', 'E', 'E', 'E',
        'F',
        'G',
        'H',
        'I', 'I', 'I', 'I',
        'J',
        'K', 'K', 'K',
        'L', 'L',
        'M',
        'N', 'N', 'N',
        'O',
        'P',
        'Q',
        'R', 'R', 'R',
        'S', 'S',
        'T', 'T',
        'U', 'U', 'U', 'U',
        'V',
        'W',
        'X',
        'Y',
        'Z'
    };
    public static List<char> portugueseAlphabet = new()
    {
        'A', 'A', 'A', 'A', 'A',
        'B',
        'C',
        'D',
        'E', 'E', 'E', 'E', 'E',
        'F',
        'G',
        'H',
        'I', 'I', 'I', 'I',
        'J',
        'L', 'L',
        'M',
        'N', 'N', 'N',
        'O', 'O', 'O', 'O',
        'P',
        'Q',
        'R', 'R', 'R',
        'S', 'S', 'S',
        'T', 'T',
        'U', 'U',
        'V',
        'X',
        'Z',
        'Á',
        'Â',
        'Ã',
        'À',
        'Ç',
        'É',
        'Ê',
        'Í',
        'Ó',
        'Ô',
        'Õ',
        'Ú'
    };
    public static List<char> franceAlphabet = new()
    {
        'A', 'A', 'A', 'A', 'A',
        'B',
        'C',
        'D',
        'E', 'E', 'E', 'E', 'E',
        'F',
        'G',
        'H',
        'I', 'I', 'I', 'I',
        'J',
        'K',
        'L', 'L',
        'M',
        'N', 'N', 'N',
        'O', 'O', 'O', 'O',
        'P',
        'Q',
        'R', 'R', 'R',
        'S', 'S', 'S',
        'T', 'T',
        'U', 'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'É',
        'À',
        'È',
        'Ù',
        'Ë',
        'Ü',
        'Ï',
        'Â',
        'Ê',
        'Î',
        'Ô',
        'Û',
        'Ç',
        'Æ',
        'Œ'
    };
    public static List<char> spanishAlphabet = new()
    {
        'A', 'A', 'A', 'A', 'A',
        'B',
        'C',
        'D', 'D',
        'E', 'E', 'E', 'E', 'E',
        'F',
        'G',
        'H',
        'I', 'I', 'I', 'I',
        'J',
        'K',
        'L', 'L',
        'M',
        'N', 'N', 'N',
        'O', 'O', 'O', 'O',
        'P',
        'Q',
        'R', 'R', 'R',
        'S', 'S', 'S',
        'T',
        'U', 'U',
        'V',
        'W',
        'X',
        'Y',
        'Z',
        'Á',
        'É',
        'Í',
        'Ó',
        'Ú',
        'Ü'
    };
    public static List<char> russianAlphabet = new()
    {
        'A', 'A', 'A', 'A',
        'Б',
        'В', 'В',
        'Г',
        'Д',
        'Е', 'Е', 'Е', 'Е', 'Е',
        'Ё',
        'Ж',
        'З',
        'И', 'И', 'И', 'И',
        'Й',
        'К',
        'Л', 'Л',
        'М',
        'Н', 'Н', 'Н',
        'О', 'О', 'О', 'О', 'О',
        'П',
        'Р', 'Р',
        'С', 'С', 'С',
        'Т', 'Т', 'Т',
        'У',
        'Ф',
        'Х',
        'Ц',
        'Ч',
        'Ш',
        'Щ',
        'Ъ',
        'Ы',
        'Ь',
        'Э',
        'Ю',
        'Я'
    };
}
